return {
  manifest_version = 1,
  type = "program",
  name = "inventory-coordinator",
  version = "0.2.0",
  source_prefix = nil,
  bin = "src/main.lua",
  install_script = "install/setup.lua",
  files = {
    "README.md",
    "install/setup.lua",
    "install/templates/config.lua",
    "src/main.lua",
    "src/app/release_service.lua",
    "src/app/runtime.lua",
    "src/app/wizard.lua",
    "src/infra/persistence.lua",
    "src/model/config.lua",
    "src/model/cycle.lua",
    "src/model/plan.lua",
    "src/model/schedule.lua",
    "src/model/transfer_queue.lua",
    "src/model/warehouse_registry.lua",
    "src/ui/controller.lua",
    "src/ui/coordinator_view.lua",
    "src/ui/detail_view.lua",
    "src/ui/fmt.lua",
    "src/ui/summary_model.lua",
    "src/ui/summary_view.lua",
  },
  deps = {
    log              = { version = "0.1.0" },
    rednet_contracts = { version = "0.1.1" },
  },
  dev_deps = {
    luaunit = { version = "3.4" },
  },
}
